name: Test Workflow Pierre

on:
  push:

jobs:
  echo-test: 
    runs-on: ubuntu-latest

    steps: 
      - name: Echo the name
        run: | 
          export NAME=Pierre
          echo the $NAME